version: '2'

services:

  celredis1:
    hostname: redis1
    image: redis:4.0.5-alpine
    labels:
      NAME: "redis1"
    ports:
      - "6379:6379"
      - "16379:16379"
    container_name: "celredis1"
    # volumes:
      # want to store the rdb file outside the container?
      # - /backedupdironhost:/opt/redis/run
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

  # RabbitMQ
  celrabbit1:
    image: "rabbitmq:3.6.6-management"
    hostname: "rabbit1"
    env_file:
      - ./env/rabbit1-dev.env
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    labels:
      NAME: "rabbit1"
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    container_name: "celrabbit1"
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

