version: '2'

services:

  # Celery Connectors
  mixinloadtest:
    hostname: mixinloadtest
    image: jayjohnson/celery-connectors:latest
    env_file: ./env/common-celery-connectors.env
    environment:
      - APP_NAME=mixin-load-test-ecomm-rabbit
      - SUBSCRIBER_NAME=mixin-load-test-sub
      - SUB_BROKER_URL=
      - CONSUME_EXCHANGE=
      - CONSUME_ROUTING_KEY=
      - CONSUME_QUEUE=
      - PUBLISH_NAME=mixin-load-test-publisher
      - PUB_BROKER_URL=pyamqp://rabbitmq:rabbitmq@localhost:5672//
      - PUBLISH_EXCHANGE=ecomm.api
      - PUBLISH_EXCHANGE_TYPE=topic
      - PUBLISH_ROUTING_KEY=ecomm.api.west
      - PUBLISH_QUEUE=ecomm.api.west
      - NUM_MSG_TO_PUBLISH=20000
    labels:
      NAME: "mixinloadtest"
    container_name: "mixinloadtest"
    network_mode: "host"
    # volumes:
      # want to shared files outside the container?
      # - /tmp:/opt/shared
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    # debug containers by sleeping on entrypoint
    # entrypoint: "sleep 600"
    entrypoint: "/opt/celery_connectors/venv/bin/python /opt/celery_connectors/start-mixin-load-test.py"
