version: '2'

services:

  # Celery Connectors
  ecommworker:
    hostname: ecommworker
    image: jayjohnson/celery-connectors:latest
    env_file: ./env/common-celery-connectors.env
    environment:
      - APP_NAME=celery-rabbitmq
      - SUBSCRIBER_NAME=rmq-sub
      - SUB_BROKER_URL=pyamqp://rabbitmq:rabbitmq@localhost:5672//
      - PUB_BROKER_URL=redis://localhost:6379/0
      - PATH_TO_WORKER_MODULE=ecomm_app.job_worker
      - PATH_TO_CELERY=/opt/celery_connectors/venv/bin/celery
      - APP_NAME=ecommerce_subscriber
      - NUM_WORKERS=3
      - LOG_LEVEL=DEBUG
    labels:
      NAME: "ecommworker"
    container_name: "ecommworker"
    network_mode: "host"
    # volumes:
      # want to shared files outside the container?
      # - /tmp:/opt/shared
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    # debug containers by sleeping on entrypoint
    # entrypoint: "sleep 600"
    entrypoint: "/opt/celery_connectors/start-ecomm-worker.sh"
