version: '2'

services:

  # Celery Connectors
  kombupubsqs:
    hostname: kombupubsqs
    image: jayjohnson/celery-connectors:latest
    env_file: ./env/common-celery-connectors.env
    environment:
      - SQS_AWS_ACCESS_KEY=
      - SQS_AWS_SECRET_KEY=
      - APP_NAME=kombu-sqs-pub
      - SUBSCRIBER_NAME=
      - CONSUME_EXCHANGE=
      - CONSUME_ROUTING_KEY=
      - CONSUME_QUEUE=
      - PUBLISH_NAME=kombu-sqs-pub
      - PUB_BROKER_URL=
      - PUBLISH_EXCHANGE=test1
      - PUBLISH_ROUTING_KEY=test1
      - PUBLISH_QUEUE=test1
    labels:
      NAME: "kombupubsqs"
    container_name: "kombupubsqs"
    network_mode: "host"
    # volumes:
      # want to shared files outside the container?
      # - /tmp:/opt/shared
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    # debug containers by sleeping on entrypoint
    # entrypoint: "sleep 600"
    entrypoint: "/opt/celery_connectors/venv/bin/python /opt/celery_connectors/kombu_sqs_publisher.py"
