version: '2'

services:

  # Celery Connectors
  kombumsgprocrmq:
    hostname: kombumsgprocrmq
    image: jayjohnson/celery-connectors:latest
    env_file: ./env/common-celery-connectors.env
    environment:
      - APP_NAME=rmq-msg-proc
      - SUBSCRIBER_NAME=rmq-proc
      - SUB_BROKER_URL=pyamqp://rabbitmq:rabbitmq@localhost:5672//
      - CONSUME_EXCHANGE=
      - CONSUME_ROUTING_KEY=
      - CONSUME_QUEUE=user.events.conversions
      - PUBLISH_NAME=rmq-proc
      - PUB_BROKER_URL=redis://localhost:6379/0
      - PUBLISH_EXCHANGE=reporting.accounts
      - PUBLISH_ROUTING_KEY=reporting.accounts
      - PUBLISH_QUEUE=
    labels:
      NAME: "kombumsgprocrmq"
    container_name: "kombumsgprocrmq"
    network_mode: "host"
    # volumes:
      # want to shared files outside the container?
      # - /tmp:/opt/shared
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    # debug containers by sleeping on entrypoint
    # entrypoint: "sleep 600"
    entrypoint: "/opt/celery_connectors/venv/bin/python /opt/celery_connectors/start-kombu-message-processor-rabbitmq.py"
